### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by westerlund** [westerlund/SwiftGIF#2]

**Comment by randymcrandell** [comment]
Second this.  I can't implicitly figure out how to use this.

**Comment by westerlund** [comment]
@randymcrandell I didn't know people actually used this repo, of course I'll add some additional documentation!

**Comment by randymcrandell** [comment]
appreciated!  i installed via cocoa pods but am not quite sure where the createGIF code goes.  i have a gif file that i would like to use as a button but am not sure how to incorporate.

![screenshot](https://cloud.githubusercontent.com/assets/9652320/17646100/2fc15218-616f-11e6-8dc8-1406f36ad49e.png)

thank you!

EDIT:

the project is a soundboard app where pressing the button triggers a play/pause function.  ideally, i would be able to display the GIF displayed when playing, and a still image displayed when paused.

`import UIKit
import AVFoundation

class ViewController: UIViewController {

```
let soundFilenames = ["Fool For You_v1","We're Tired","The Blancos - Find Somebody ","LA Lights 06","Cant Take Me Down v1","Bring On The Pain","Lit Up 04","Target Pratice 02"]
var audioPlayers = [AVAudioPlayer]()

override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view, typically from a nib.


    //  Set up audio players
    for sound in soundFilenames {

        do {

            //Try something (Only if method THROWS)
            let url = NSURL(fileURLWithPath: NSBundle.mainBundle().pathForResource(sound, ofType: "mp3")!)
            let audioPlayer = try AVAudioPlayer(contentsOfURL: url)

            audioPlayers.append(audioPlayer)
        }

        catch {
            audioPlayers.append(AVAudioPlayer())
        }



    }
}

override func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
}

@IBAction func buttonTapped(sender: UIButton) {

    // Get the audioPlayer
    let audioPlayer = audioPlayers[sender.tag]
    if (!sender.selected) {
        audioPlayer.play()
    }
    else {
        audioPlayer.pause()
    }
sender.selected = !sender.selected
```

}
}`

**Comment by westerlund** [comment]
@randymcrandell Oh, I'm sorry, but this utility is only for creating a GIF file from a set of UIImages. For displaying GIFs, I recommend checking out FLAnimatedImage, https://github.com/Flipboard/FLAnimatedImage, it's tested and stable for production!
